# HoneyChest Configuration file
# @author syamn <admin@sakura-server.net>
# BukkitDev: http://dev.bukkit.org/server-mods/honeychest/

#==================#
#   Basic Config   #
#==================#
# ItemID, used to create/remove honeychest
toolID: 269

# Take action when plugin caught steal items from honeychest
# Valid actions: kick, ban, command
takeAction: kick

# Set to true for MCBans/glizer global bans. Be sure to follow their guidelines
# Set "takeAction: ban" and use MCBans or glizer if you want to use this option
globalBan: false

# Take commands from console if set takeAction: command
# "!player!" string is replaced by caught player name.
commands:
- "jail !player! 3m"
- "say !player! has been jailed because steal items from honeychest!"

# Rollback inventory when we detect the theft (Use ItemID:data only)
rollback: true

# Remove dropped items when player opening honeychest
removeDropped: false

#====================#
#   Logging Config   #
#====================#
logToFile: true
logItems: true
logPath: plugins/Honeychest/honeychest.log

#=====================#
#   Messages Config   #
#=====================#
# There is a language file in English(default) and Japanese(ja_jp)
# If you want, you can create a custom message file in your language
messageLocale: default
# If it is true, hide some messages gives a hint for griefer
# For example, notBreakTrap, notPlaceChest and openedTrap messages on language file
hideTrapMessages: false
# If it is true, broadcast stolen items.
broadcastItems: true
# If it is true, hide "PlayerListener.youAreIgnore" message on language file
hideIgnoreMessage: true

#===================#
#   Reason Config   #
#===================#
honeychestKickReason: '[Honeychest] You have been caught steal items from honeychest.'
# If you set globalBAN: true, need to use the English here for their guidelines
# "!location!" string is replaced by "worldname:x,y,y"
honeychestBanReason: 'Steal items from HoneyChest. (!location!)'


#==================#
#   DO NOT TOUCH   #
#==================#
# Do not touch this option! It is a check if you are running the recent configuration version
version: ${project.version}
