##  Plugin Information  ##
name: Honeychest
version: 0.99
main: syam.Honeychest.Honeychest
description: Anti-Grief Plugin! Can be able to create chest of honeypot!
website: http://sakura-server.net/
softdepend: [MCBans]
##  Original Author     ##
author: syam
commands:
    honeychest:
      usage: /honeychest help - to see the help
      aliases: [hc]
      description: To see the Honeychest help.
permissions:
    honeychest.admin:
        default: op
        description: Can create/break honeychest.
    honeychest.ignore:
        default: op
        description: Can remove items from honeychest.